export default  ReduxConstants = {
    SET_NAVIGATE:1,
    SEND_AUTH_REQUEST:2,
    RECEIVE_RESPONE:3,
    CHANGE_USER_INFO:4,
    CHANGE_ERROR:5,
    CLEAN_ERROR:6,

    ADD_CATEGORY:7,
    EDIT_CATEGORY:8,

    ADD_SUB_CATEGORY:9,
    EDIT_SUB_CATEGORY:10,

    ADD_PROPERTY:11,
    EDIT_PROPERTY:12,

    ADD_SUB_CATEGORY_PROPERTY:13,
    EDIT_SUB_CATEGORY_PROPERTY:14,

    ADD_PRODUCT:15,
    EDIT_PRODUCT:16,
    REMOVE_PRODUCT:17,
    CHANGE_SELECTED_PRODUCT:'CHANGE_SELECTED_PRODUCT',

    ADD_PRODUCT_PROPERTY:'ADD_PRODUCT_PROPERTY',
    EDIT_PRODUCT_PROPERTY:'EDIT_PRODUCT_PROPERTY',
    REMOVE_PRODUCT_PROPERTY:'REMOVE_PRODUCT_PROPERTY',

    ADD_NEW_PRODUCT_PROPERTY:'ADD_NEW_PRODUCT_PROPERTY',
    EDIT_NEW_PRODUCT_PROPERTY:'EDIT_NEW_PRODUCT_PROPERTY',
    CLEAN_NEW_PRODUCT_PROPERTY:'CLEAN_NEW_PRODUCT_PROPERTY',

    CHANGE_SELECTED_CATEGORY:18,
    CHANGE_SELECTED_SUB_CATEGORY:19,

    CHANGE_NEW_PRODUCT:20,
    CLEAN_NEW_PRODUCT:'CLEAN_NEW_PRODUCT',

    ADD_FACTOR:21,
    CHANGE_NEW_FACTOR:22,

    CHANGE_MESSAGE:23,
    CLEAN_MESSAGE:24,

    CHANGE_NEW_CATEGORY:25,
    CHANGE_NEW_SUB_CATEGORY:26,
    
    CHANGE_NEW_PROPERTY:27,

    CHANGE_SEARCH:'CHANGE_SEARCH',

    ADD_ORDER_FACTOR:'ADD_ORDER_FACTOR',
    ADD_ORDERS:'ADD_ORDERS',
    EDIT_NEW_ORDER_FACTOR:'EDIT_NEW_ORDER_FACTOR',
    CLEAR_NEW_ORDER_FACTOR:'CLEAR_NEW_ORDER_FACTOR',
    ADD_NEW_ORDER:'ADD_NEW_ORDER',
    CLEAR_NEW_ORDERS:'CLEAR_NEW_ORDERS',


    CHANGE_SELECTED_ORDER_FACTOR:'CHANGE_SELECTED_ORDER_FACTOR',
    CHANGE_SELECTED_FACTOR:'CHANGE_SELECTED_FACTOR',

    ADD_USER:'ADD_USER',
    CHANGE_NEW_USER:'CHANGE_NEW_USER',
    CLEAN_NEW_USER:'CLEAN_NEW_USER',

    'ADD_EXPENSE':'ADD_EXPENSE',
    'CHANGE_NEW_EXPENSE':'CHANGE_NEW_EXPENSE',
    'CLEAN_NEW_EXPENSE':'CLEAN_NEW_EXPENSE'
}